// <auto-generated />
namespace XykChat.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class added_RoomJoin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_RoomJoin));
        
        string IMigrationMetadata.Id
        {
            get { return "202111260227346_added_RoomJoin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
