// <auto-generated />
namespace XykChat.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class updated_room : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_room));
        
        string IMigrationMetadata.Id
        {
            get { return "202111231534265_updated_room"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
